
OBJ	=	CBuffer.obj CImage.obj CQualityMeasures.obj

EXTRAFLAGS = /EHsc -I..\Inc -I..\..\DISE -D"WIN32"
CFLAGS =  $(EXTRAFLAGS)
CPPFLAGS = $(CFLAGS) -DNOMINMAX

default:	$(OBJ)
	copy *.obj ..\..\xRITDecompress

clean:
	-del *.obj

