
OBJ	= CHOptim.obj CHcodec.obj CHufftables.obj CJBlock.obj CJPEGDecoder.obj CJPEGLossLessCoder.obj CJPEGLossyCoder.obj CQuantizationTable.obj CompressJPEG.obj

EXTRAFLAGS = /EHsc -I..\Inc -I..\..\..\DISE -I..\..\Inc -D"WIN32" 
CFLAGS =  $(EXTRAFLAGS)
CPPFLAGS = $(CFLAGS)

default:	$(OBJ)
	copy *.obj ..\..\..\xRITDecompress

clean:
	-del *.obj

