name: "CI build"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 5 3,17 * *'

jobs:
  CIBW:
    uses: sbrodehl/pyPublicDecompWT/.github/workflows/cibuildwheel.yml@main
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
